COMP3710 Project
Robin Rana          T00743614
Kyle Dobi           T00728238
Nikita Chaudhary    T00723204  
Edilson Chi         T00736171

Week_2

Importing pandas library

In [1]:
import pandas as pd

Initially there isnt a pandas lib pre installed in our vs code hence why this showed the error
So the code below installs and loads the library sucessfully.

In [2]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\robin\appdata\local\programs\python\python313\lib\site-packages (3.0.6)
Requirement already satisfied: numpy>=1.26.0 in c:\users\robin\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.5.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\robin\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\robin\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.5 in c:\users\robin\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd


Now since the instruction was to: Use pandas to load the files, display the first few rows, check their dimensions and data types, and summarize missing values.

We create 2 tables for 2 files: 
Supplementary File 2: Resistome sequencing sample metadata. we name it simply metadata
-It describe the samples.

Supplementary File 4: Resistome sequencing count matrix. We name it counts.
-This matrix contains numerical measurements associated with resistance genes.

In [4]:
#Simple file reading syntax

metadata = pd.read_csv('Table_2.csv')
count = pd.read_csv('Table_4.csv')

Displaying First Few rows

We're using the command "tablename.head()"
It only displays the first 5 rows by default.

In [5]:
display(metadata.head())
display(count.head())

,Supplementary File 2) Resistome sequencing sample metadata.,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37
0,ID,Group,AMR_seq_pool,microbiome_seq_pool,Group_num,Sample_type,Time,AMR_raw_paired_reads,AMR_QC_paired_reads,AMR_filter_removed,...,parenteral_phenicol_ADD,parenteral_fluoroquinolones_ADD,parenteral_sulfonamide_ADD,parenteral_tetracycline_ADD,resistome_raw_mapped_reads,resistome_CSS_counts,AMR_class_Richness,AMR_class_Shannon,AMR_mech_Richness,AMR_mech_Shannon
1,IA13,Individual - 1st time point,Pool 3,Pool 1,5,Individual,1st time point,6885106,6770930,2631898,...,0,0,0,0,198122,11703.80435,14,1.584569033,33,2.503078592
2,IA15,Individual - 1st time point,Pool 3,Pool 1,7,Individual,1st time point,13336698,12767024,2284528,...,0,0,0,0,333501,13689.95526,15,1.559313314,38,2.365297795
3,IA16,Individual - 1st time point,Pool 3,Pool 1,8,Individual,1st time point,18194281,17000763,2700726,...,0,0,0,0,444509,16864.93152,16,1.82386958,44,2.62811881
4,IA19,Individual - 1st time point,Pool 2,Pool 3,10,Individual,1st time point,22268461,21756652,8477613,...,0,0,0,0,300105,11828.66265,16,1.529849017,41,2.129264993

,Supplementary File 4) Resistome sequencing count matrix.,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 183,Unnamed: 184,Unnamed: 185,Unnamed: 186,Unnamed: 187,Unnamed: 188,Unnamed: 189,Unnamed: 190,Unnamed: 191,Unnamed: 192
0,NaN,PA49,IA30,PE48,IA71,IA47,IA15,IE30,PA25,PE26,...,IA51,PE44,PE28,PA20,IE47,IA34,PS9,PE47,PS5,IE36
1,MEG_1000|Drugs|Aminoglycosides|Aminoglycoside_...,427,13,605,0,67,127,232,581,623,...,0,473,325,654,43,0,167,738,221,0
2,MEG_1001|Drugs|Aminoglycosides|Aminoglycoside_...,157,0,54,0,0,0,0,61,61,...,0,62,80,46,175,0,31,26,88,0
3,MEG_1002|Drugs|Aminoglycosides|Aminoglycoside_...,25,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,MEG_1003|Drugs|Aminoglycosides|Aminoglycoside_...,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

Gang Im so happy this worked. :) BROTHERRRRRR!

Okay back to track

Now, we are visualizing both table as a matrix.
Checking their dimensions:  

In pandas Library, we use command tablename.shape
this returns (#_of_rows, #_of_columns )

In [6]:
print("Metadata dimensions:", metadata.shape)
print("Count dimensions:", count.shape)

Metadata dimensions: (193, 38)
Count dimensions: (1423, 193)

Life feels great when code runs smoooth. 

Checking their datatypes
command used : tablename.info()
.info() displays its name, the # of non missing entries, and its data type.

In [7]:
metadata.info()

<class 'pandas.DataFrame'>
RangeIndex: 193 entries, 0 to 192
Data columns (total 38 columns):
 #   Column                                                       Non-Null Count  Dtype
---  ------                                                       --------------  -----
 0   Supplementary File 2) Resistome sequencing sample metadata.  193 non-null    str
 1   Unnamed: 1                                                   193 non-null    str
 2   Unnamed: 2                                                   193 non-null    str
 3   Unnamed: 3                                                   193 non-null    str
 4   Unnamed: 4                                                   193 non-null    str
 5   Unnamed: 5                                                   193 non-null    str
 6   Unnamed: 6                                                   193 non-null    str
 7   Unnamed: 7                                                   193 non-null    str
 8   Unnamed: 8                                                   193 non-null    str
 9   Unnamed: 9                                                   193 non-null    str
 10  Unnamed: 10                                                  193 non-null    str
 11  Unnamed: 11                                                  193 non-null    str
 12  Unnamed: 12                                                  193 non-null    str
 13  Unnamed: 13                                                  193 non-null    str
 14  Unnamed: 14                                                  193 non-null    str
 15  Unnamed: 15                                                  193 non-null    str
 16  Unnamed: 16                                                  193 non-null    str
 17  Unnamed: 17                                                  193 non-null    str
 18  Unnamed: 18                                                  193 non-null    str
 19  Unnamed: 19                                                  193 non-null    str
 20  Unnamed: 20                                                  193 non-null    str
 21  Unnamed: 21                                                  95 non-null     str
 22  Unnamed: 22                                                  193 non-null    str
 23  Unnamed: 23                                                  193 non-null    str
 24  Unnamed: 24                                                  193 non-null    str
 25  Unnamed: 25                                                  193 non-null    str
 26  Unnamed: 26                                                  193 non-null    str
 27  Unnamed: 27                                                  193 non-null    str
 28  Unnamed: 28                                                  193 non-null    str
 29  Unnamed: 29                                                  193 non-null    str
 30  Unnamed: 30                                                  193 non-null    str
 31  Unnamed: 31                                                  193 non-null    str
 32  Unnamed: 32                                                  193 non-null    str
 33  Unnamed: 33                                                  193 non-null    str
 34  Unnamed: 34                                                  193 non-null    str
 35  Unnamed: 35                                                  193 non-null    str
 36  Unnamed: 36                                                  193 non-null    str
 37  Unnamed: 37                                                  193 non-null    str
dtypes: str(38)
memory usage: 57.4 KB

In [8]:
count.info()

<class 'pandas.DataFrame'>
RangeIndex: 1423 entries, 0 to 1422
Columns: 193 entries, Supplementary File 4) Resistome sequencing count matrix. to Unnamed: 192
dtypes: str(193)
memory usage: 2.1 MB

Summarizing Missing Values

we use the command .isna(): This checks cells w missingg values

and then to summarize we simply are going to use the .sum() function

In [9]:
print("Missing values in each column of metadata:")
display(metadata.isna().sum())

Missing values in each column of metadata:

Supplementary File 2) Resistome sequencing sample metadata.     0
Unnamed: 1                                                      0
Unnamed: 2                                                      0
Unnamed: 3                                                      0
Unnamed: 4                                                      0
Unnamed: 5                                                      0
Unnamed: 6                                                      0
Unnamed: 7                                                      0
Unnamed: 8                                                      0
Unnamed: 9                                                      0
Unnamed: 10                                                     0
Unnamed: 11                                                     0
Unnamed: 12                                                     0
Unnamed: 13                                                     0
Unnamed: 14                                                     0
Unnamed: 15                                                     0
Unnamed: 16                                                     0
Unnamed: 17                                                     0
Unnamed: 18                                                     0
Unnamed: 19                                                     0
Unnamed: 20                                                     0
Unnamed: 21                                                    98
Unnamed: 22                                                     0
Unnamed: 23                                                     0
Unnamed: 24                                                     0
Unnamed: 25                                                     0
Unnamed: 26                                                     0
Unnamed: 27                                                     0
Unnamed: 28                                                     0
Unnamed: 29                                                     0
Unnamed: 30                                                     0
Unnamed: 31                                                     0
Unnamed: 32                                                     0
Unnamed: 33                                                     0
Unnamed: 34                                                     0
Unnamed: 35                                                     0
Unnamed: 36                                                     0
Unnamed: 37                                                     0
dtype: int64

In [10]:
print("Missing values in each column of count:")
display(count.isna().sum())

Missing values in each column of count:

Supplementary File 4) Resistome sequencing count matrix.    1
Unnamed: 1                                                  0
Unnamed: 2                                                  0
Unnamed: 3                                                  0
Unnamed: 4                                                  0
                                                           ..
Unnamed: 188                                                0
Unnamed: 189                                                0
Unnamed: 190                                                0
Unnamed: 191                                                0
Unnamed: 192                                                0
Length: 193, dtype: int64